version: "3.4"

services:
  send:
    image: send
    links:
     - rabbitmq
    restart: on-failure
    build:
      context: .
      dockerfile: Send/Dockerfile

  receive:
    image: receive
    links:
      - rabbitmq
    restart: on-failure
    build:
      context: .
      dockerfile: Receive/Dockerfile

  rabbitmq:
    image: rabbitmq:latest
    expose:
      - 5672
      - 15672
    ports: 
      - 5672:5672
      - 15672:15672
